name: tatsam
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.1
  http: ^0.13.5
  equatable: ^2.0.3
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.15
  image_picker: ^0.7.4
  permission_handler: ^8.3.0
  universal_io: 2.0.4
  http_parser: ^4.0.1
  azlistview: ^2.0.0-nullsafety.0
  flutter_slidable: ^1.3.2
  
  # FIREBASE
  firebase_core: ^1.2.0
  firebase_auth: ^3.3.8
  cloud_firestore: ^3.1.7

dependency_overrides:
  firebase_auth_platform_interface: 6.1.11
  cloud_firestore_platform_interface: 5.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 400
    - family: AlegreyaSans
      fonts:
        - asset: assets/fonts/AlegreyaSansSC-Regular.ttf
          weight: 400
